Dir[File.join(__dir__, "helpers", "*.rb")].each { |f| require f }


XCODEPROJ = "ios/FeriasControlTemp.xcodeproj"
XCODEWORKSPACE = "./ios/FeriasControlTemp.xcworkspace"
SCHEME = "FeriasControlTemp"

GRADLE_FILE = "./android/app/build.gradle"

# -------------------------
# CORE RELEASE LOGIC
# -------------------------
lane :release_core do
  # ensure_git_status_clean

  # 1️⃣ iOS versioning (FASTLANE DSL — correto aqui)
  increment_build_number(xcodeproj: XCODEPROJ)

  increment_version_number(
    xcodeproj: XCODEPROJ,
    version_number: Versioning.version
  )

  # 2️⃣ Sync Android versionCode with iOS build number
  build_number = get_build_number(xcodeproj: XCODEPROJ)

  android_set_version_code(version_code: build_number, gradle_file: GRADLE_FILE)	

  android_set_version_name(version_name: Versioning.version, gradle_file: GRADLE_FILE)


  # 3️⃣ Tag
  tag = "v#{Versioning.version}+#{build_number}"

  # 4️⃣ Changelog
  changelog = changelog_from_git_commits(pretty: "- %s (%h)", merge_commit_filtering: "exclude_merges")
  UI.abort_with_message!("No changes to release") if changelog.strip.empty?

  Versioning.update_changelog!(tag: tag, changelog: changelog)

  # 5️⃣ Commit + tag + push
  commit_version_bump(
    message: "release: {tag} 🚀",
    xcodeproj: XCODEPROJ,
    include: [
      "CHANGELOG.md",
      XCODEPROJ,
      GRADLE_FILE,
    ]
  )

  add_git_tag(tag: tag)
  push_to_git_remote
  push_git_tags
end

# -------------------------
# BUILD LANES
# -------------------------
platform :ios do
lane :build_ios do
  build_app(
    workspace: XCODEWORKSPACE,
    scheme: SCHEME
  )
end
end

platform :android do
lane :build_android do
  UI.message("--- Building Android 🤖")

  gradle(task: 'clean', project_dir: 'android/')

  gradle(
    task: "assemble",
    ## Necessário pois o Fastfile executa da
    ## raiz do projeto, e o build.gradle está na pasta android

    project_dir: "./android", 
    print_command_output: true,
    print_command: true,
    build_type: "Release"
  )

  UI.message("--- Android built successfully 🎉")
end
end


